"""msg_id_type

迁移 ID: bb58fca761ea
父迁移: e63054f23a7e
创建时间: 2024-08-29 15:39:52.921535

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "bb58fca761ea"
down_revision: str | Sequence[str] | None = "e63054f23a7e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_argot_argot", schema=None) as batch_op:
        batch_op.alter_column(
            "message_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_argot_argot", schema=None) as batch_op:
        batch_op.alter_column(
            "message_id",
            existing_type=sa.String(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
